// <auto-generated />
namespace ReedHampton.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DevelopmentProject100 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DevelopmentProject100));
        
        string IMigrationMetadata.Id
        {
            get { return "201707102018218_DevelopmentProject1.0.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
